[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "toraheval"
version = "0.1.0"
requires-python = ">=3.10"
description = "Torah evaluation suite for testing model understanding of Torah concepts"
readme = "README.md"
license = {text = "MIT"}
authors = [
    { name = "Matanya Loewenthal", email = "matanya@sofer.ai" },
    { name = "Zach Fish", email = "zach@sofer.ai" },
]
dependencies = [
    "datasets==4.0.0",
    "autoevals>=0.0.14",
    "openai>=1.0.0",
    "pydantic-settings==2.9.1",
    "deepeval>=3.3.5",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
include = ["toraheval*"]
